### ISSUE TITLE
[Enhancement] Use Avenir Next for Storybook text content

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#136]
Is it possible to use our brand font in the component library for the text content (documentation)? If yes are there pros and cons related to doing this? Benefits and trade-offs?

**Comment by meissadia** [comment]
Possible solution: https://mushti-dev.medium.com/hey-e6faa20b910a

**Comment by meissadia** [comment]
@natalia-fitzgerald Is the idea here to use Avenir Next for *all* text in Storybook? i.e. Not just our components

**Comment by natalia-fitzgerald** [comment]
Yes, my idea was to use Avenir Next for all the text in Storybook (or at least as much as possible within the CFPB component library).

**Comment by meissadia** [comment]
Seems like this would fit into [theming](https://storybook.js.org/docs/7.2/react/configure/theming) Storybook
