### ISSUE TITLE
[Component] Checkbox

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#141]
# [Checkbox](https://cfpb.github.io/design-system/components/checkboxes)

Tracking the design and development lifecycle of the checkbox component. 

### Related links: 
- https://cfpb.github.io/design-system/components/buttons
- https://cfpb.github.io/design-system/development/variables#buttons
- https://cfpb.github.io/design-stories/?path=/docs/components-button--docs
 
#### Effort level: Large
(Levels: Small, Medium, Large, Extra Large)

###  Checklist
- [X] The component has an identified use case (one of the 3 options below)
- [X] The current state of the component has been identified (one of the 3 options below)
- [X] The task is broken into steps

### Identify the use case: 
- [X] Small business lending filing platform 
- [ ] Metro 2 tool
- [ ] No identified project need but does exist in the CFPB Design System

### Identify the current state:
- [X] The component already exist in the CFPB Design System  
  - Build an exact React translation of the CFPB Design System component
  - Build the component in Figma (if it is not already included in the CFPB Design System template)

- [ ] The component does not exist in the CFPB Design System but does exist on cf.gov 
  - Conduct a design audit of any component variations that exist on our website (if applicable)
  - Determine final design
  - Build the component in Figma (if it is not already included in the CFPB Design System template)
  - Add the component to UI component library
  - Incorporate the component into the CFPB Design System or alert the CFPB Design System maintainers that this component will need to be added.

- [ ] The component does not exist in the CFPB Design System or on cf.gov (but has an identified use case and is being tracked as part of the SBL or M2 work)
  - Design the component as a part of the SBL or Metro 2 project work
  - Build the component in Figma (if it is not already included in the CFPB Design System template)
  - Add the component to UI component library
  - Incorporate the component into the CFPB Design System or alert the CFPB Design System maintainers that this component will need to be added.

#### Types
- [X] Standard checkboxes
  - [x] Default
  - [x] Focused
  - [x] Selected
  - [x] Hover
  - [x] Disabled
  - [x] Disabled selected

- [X] Large target area checkboxes
  - [x] Default
  - [x] Focused
  - [x] Selected
  - [x] Hover
  - [x] Disabled

### Component is fully functional
- [ ] Visual regression testing has been conducted
- [ ] All interactive states are accounted for and incorporated 
- [ ] The component is successfully integrated into the Small business lending filing platform (or prototype) or other CFPB  web app

### Accessibility checks have been completed
- [ ] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Component is screen reader friendly
- [ ] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

### For existing components: 
- [ ] React component visually and functionally matches the CFPB Design System component 
- [ ] Visual regression testing has been conducted and component has passed all tests
- [ ] Manual visual review has been conducted and component has passed this review
- [ ] Storybook page includes all types and variations of the component that are included in the CFPB Design System

### For new components: 
- [ ] The CFPB Design System maintainers have been alerted that there is a new component that must be added to the system OR
- [ ] We have added the new components to the CFPB Design System
- [ ] Documentation has been written and is included in Storybook and/or the CFPB Design System

### Final sign off
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

**Comment by natalia-fitzgerald** [comment]
**Content updates:** 
- [ ] Change all title case to sentence case (global change)
  - For example: "Default checkbox" instead of "Default Checkbox"  
- [ ] Change "Large Checkbox" to "Large target checkbox"  

Things to check: 
- [ ] Check on use cases for "Checkbox with helper" and "Large checkbox with helper". Is there a known use case for our project or on the cf.gov?

**Comment by meissadia** [comment]
@natalia-fitzgerald 
 
> Indicate which types we will include in the React component library.

Should each of these types be a separate story (demonstration of how to create it)? Or a separate component (a reusable implementation of this variant)?

**Comment by meissadia** [comment]
Separate issue to change Story names to sentence case to other components. 
 
https://github.com/cfpb/design-stories/issues/156

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Below is a checklist of Design System checklist components. In the Design System they are grouped as types and then by states. 

**Type:** Standard checkboxes
**States:** Default, Focused, Selected, Hover, Disabled, Disabled selected

**Type:** Large target area checkboxes
**States:** Default, Focused, Selected, Hover, Disabled

I'm not sure why the large target area checkbox in the Design System live code doesn't show a Disabled selected state. I think this is an error in the live text code block because I see code for it in the HTML. So I'm going to assume we should include it in our library. I added it to the list below. 

I don't know where we should incorporate the checkbox with helper text or large target checkbox with helper text. Maybe we should create a [Fieldset component](https://cfpb.github.io/design-system/components/fieldsets)instead (like what's in the Design System)? 

I am exploring options for how we organize Storybook here: https://github.com/cfpb/design-stories/issues/155#issue-1852156863. Can you point me to visuals of the 3 options you mention here: https://github.com/cfpb/design-stories/issues/141#issuecomment-1681114343 

#### Types
##### Standard checkboxes
  - [ ] Default
  - [ ] Focused
  - [ ] Selected
  - [ ] Hover
  - [ ] Disabled
  - [ ] Disabled selected

##### Large target area checkboxes
  - [ ] Default
  - [ ] Focused
  - [ ] Selected
  - [ ] Hover
  - [ ] Disabled selected

**Comment by natalia-fitzgerald** [comment]
@meissadia 
In thinking about how we should organize and group content like checkboxes we should review/discuss: 

## Carbon
Guidelines: https://carbondesignsystem.com/components/checkbox/usage/
Storybook: https://react.carbondesignsystem.com/?path=/docs/components-checkbox--overview

## UK.gov
Guidelines: https://design-system.service.gov.uk/components/checkboxes/
Storybook: https://govuk-react.github.io/govuk-react/?path=/story/checkbox--default

## VA
Guidelines: https://design.va.gov/components/form/checkbox
Storybook: https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default
Storybook: https://design.va.gov/storybook/?path=/docs/components-va-checkbox-group--default

## USWDS
Guidelines: https://designsystem.digital.gov/components/checkbox/
Storybook: https://trussworks.github.io/react-uswds/?path=/story/components-checkbox--default-checkbox

**Comment by natalia-fitzgerald** [comment]
@meissadia 
The USWDS Checkbox organization looks clear to me. I think it's fine to include the Checkbox with helper text in the Checkbox section. But, I am not aware of any actual use cases for that variation on our website.

It looks like the USWDS has a section called "Form components" and "Fieldsets" is a subsection of that. Would you want to organize things that way?

**Comment by meissadia** [comment]
> It looks like the USWDS has a section called "Form components" and "Fieldsets" is a subsection of that. Would you want to organize things that way?

@natalia-fitzgerald That works for me, plus it aligns with the way the CFPB DS organizes them: `Components > Form Elements > Fieldsets`
 
Sidenote: PR https://github.com/cfpb/design-system-react/pull/163 adds the `Disabled selected` [states mentioned above](https://github.com/cfpb/design-system-react/issues/141#issuecomment-1681320617) and fixes some styling issues with the focus/hover variants.

**Comment by natalia-fitzgerald** [comment]
This component has been verified. I am closing this issue.
