### ISSUE TITLE
[Process] Design System updates pushed to React component library

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#144]
Define the process for bringing Design System updates into the React component library. 

## Current behavior
Latest Design System updates are not showing up in the React component library):
- Update to the size of the round SVG status icons 
- Update that removes the max width of 1 em from SVG viewBox

## Expected behavior
- Updates from the Design System are pushed to the React component library

**Comment by meissadia** [comment]
## Updating the DS version used in DSR

1) Create a PR in DSR that updates the DS library version
```
git checkout main
git pull --rebase
git checkout -b update-cfpb-ds
yarn up @cfpb/cfpb-design-system
yarn up @cfpb/cfpb-expandables
yarn up @cfpb/cfpb-forms
git add --all
git commit -m 'chore: Update CFPB DS to <new.version.number>'
git push
```

2) Review & merge the PR

3) Upon merge, updates would be auto-deployed to [cfpb.github.io/design-stories/](https://cfpb.github.io/design-stories/)

**Comment by meissadia** [comment]
Note to self: Need to integrate the above ^^^^ into the DSR documentation

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Now that we're adding more content to the intro page in Storybook should we prioritize this for the next sprint?

**Comment by meissadia** [comment]
@natalia-fitzgerald Yes! That would be a great home for this info

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Do we have a process in place now? If so should we close this issue?
