### ISSUE TITLE
[Component] Lead paragraph

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#157]
# [Lead paragraph](https://cfpb.github.io/design-system/foundation/paragraphs#lead-paragraph)
Tracking the design and development lifecycle of the lead paragraph component

### Related links: 
- **Design System (Documentation):** https://cfpb.github.io/design-system/patterns/text-introductions#standard-text-introduction
- **Design System (Codebase):** https://github.com/cfpb/design-system

| HTML | Specs |  
|------------| ------------|
|<img width="853" alt="Screenshot 2023-08-17 at 3 04 10 PM" src="https://github.com/cfpb/design-stories/assets/77348967/20ac989e-0ccc-4414-969d-281f1716fd65">|<img width="841" alt="Screenshot 2023-08-17 at 3 04 25 PM" src="https://github.com/cfpb/design-stories/assets/77348967/87dfc476-3b28-4dc9-95ee-6cbe48a3e95f">|

### Related links: 
- https://cfpb.github.io/design-system/components/buttons#disabled-buttons
 
###  Checklist
- [X] The component has an identified use case (one of the 3 options below)
- [X] The current state of the component has been identified (one of the 3 options below)
- [X] The task is broken into steps

### Identify the use case: 
- [X] Small business lending filing platform 
  - Complete user profile page: Introductory text
- [ ] Metro 2 tool
- [ ] No identified project need but does exist in the CFPB Design System

### Identify the current state:
- [X] The component already exist in the CFPB Design System  
  - Build an exact React translation of the CFPB Design System component
  - Build the component in Figma (if it is not already included in the CFPB Design System template)

- [ ] The component does not exist in the CFPB Design System but does exist on cf.gov 
  - Conduct a design audit of any component variations that exist on our website (if applicable)
  - Determine final design
  - Build the component in Figma (if it is not already included in the CFPB Design System template)
  - Add the component to UI component library
  - Incorporate the component into the CFPB Design System or alert the CFPB Design System maintainers that this component will need to be added.

- [ ] The component does not exist in the CFPB Design System or on cf.gov (but has an identified use case and is being tracked as part of the SBL or M2 work)
  - Design the component as a part of the SBL or Metro 2 project work
  - Build the component in Figma (if it is not already included in the CFPB Design System template)
  - Add the component to UI component library
  - Incorporate the component into the CFPB Design System or alert the CFPB Design System maintainers that this component will need to be added.

#### Types
- [X] Lead paragraph

### Component is fully functional
- [ ] Visual regression testing has been conducted
- [ ] All interactive states are accounted for and incorporated 
- [ ] The component is successfully integrated into the Small business lending filing platform (or prototype) or other CFPB  web app

### Accessibility checks have been completed
- [ ] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Component is screen reader friendly
- [ ] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

### For existing Design System components: 
- [ ] React component visually and functionally matches the CFPB Design System component 
- [ ] Visual regression testing has been conducted and component has passed all tests
- [ ] Manual visual review has been conducted and component has passed this review
- [ ] Storybook page includes all types and variations of the component that are included in the CFPB Design System

### For new components: 
- [ ] The CFPB Design System maintainers have been alerted that there is a new component that must be added to the system OR
- [ ] We have added the new components to the CFPB Design System
- [ ] Documentation has been written and is included in Storybook and/or the CFPB Design System

### Final sign off
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

**Comment by meissadia** [comment]
> @meissadia Would you like to pick this up as part of building out the Text introduction component?

Yes, I implemented both Paragraph variants in the TextIntroduction PR: https://github.com/cfpb/design-system-react/pull/193
