### ISSUE TITLE
Establish a process for building and finalizing React components

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#200]
@shindigira @meissadia @billhimmelsbach 

Now that we've started building out app pages it seems like a good time to reflect on what's been working and what's not working about our process for building CFPB Design System - React components. I'm specifically referring to the UI/end user/visual aspect. If work has to be done to connect the front end to the back end I am not referring to a process for that work.

I'm having trouble with switching up the process on a page by page or component by component basis. I'm finding it challenging to track and review some components within the app instead of the DSR. It would be easier for me if we can establish a general process. 

There may be instances where some things will have to be built directly in the app but I want to start with the component library whenever we can as a first step. It is better to have a page that is mostly DSR verified components so that it becomes clear what additional work needs to be done from a design perspective. It's important that as we build out the component library and the app that we are maintaining our connection to the CFPB Design System code. 

### My preferred process would be this:
- **Step 1:** Make a list of all of the components needed for a page.
- **Step 2:** Identify which components have been verified, which components are in the DSR but not verified, and which are not yet in the DSR at all.
- **Step 3:** For unverified components that are required for a page that's being built, work on finalizing that component so that it reaches the verified state.
- **Step 4:** For components that are not yet in the DSR, build those components and add to the DSR. Always start with the CFPB Design System component if one exists. 
- **Step 3:** Request UI/UX and FEWD review on the component (within the DSR)
- **Step 5:** Build the webpage using verified components

**Comment by meissadia** [comment]
Another option is to build out the SBL app's pages within the DSR Storybook first, then once they are verified, porting them over to the `sbl-frontend` repo.  This would ensure that any new components that need to be built will live in the DSR.  

It would also allow us to take advantage of the automatic deployment of preview pages that is already configured for DSR (Natalia would be able to see/interact with a live page instead of relying on screenshots).

**Comment by billhimmelsbach** [comment]
Looks pretty good to me! I have a similar question about the timing of the steps. For example, would Step 1 and Step 2 ideally be done before the ticket is assigned, or is this something the dev would do when they are assigned the ticket?

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
I could see doing Steps 1 and 2 (I could even take that on) before the dev picks up the task. Maybe we could add it as a section to the Epic issue? I'd like to go ahead and do it for the pages that are already in progress.

**Comment by natalia-fitzgerald** [comment]
We are working in this process. Moving to done.
