### ISSUE TITLE
Update SBL Figma file to use the new CFPB Design template V1.5.1

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#201]
The Design and Content team has just released a new and improved CFPB Design System - Figma library - V1.5.0. This coming sprint I will be working on updating the SBL Figma file to use the new components. Up until now the Figma file was largely built using manually built components. Moving to this new library will help to create more consistency across our Figma mock-ups, more tightly connect our library to the CFPB Design System, and allow for more efficiency as we build out mock-ups for the SBL app and shared filing platform.

**Comment by sthomas93** [comment]
@natalia-fitzgerald I think this conversation can be moved over to Enterprise or SBL Project since both are private.

**Comment by natalia-fitzgerald** [comment]
I moved this to the SBL Project repo. Closing this one.
