### ISSUE TITLE
[Prototype] User Profile page in Storybook

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-system-react#208]
Exploration of prototyping a page within Storybook. 
- Allows us to quickly identify component issues
- Takes advantage of preview deployment infrastructure for team-wide access.

User stories
- User's email domain matches one Institution
- They select the institution and hit submit => See success message

**Comment by natalia-fitzgerald** [comment]
@meissadia 
I think the prototype is surfacing some questions I have which is a good thing. 

One thing that is immediately is apparent is that some of the spacing doesn't match the Figma mock-up. I'm assuming that the spacing I do see is tied to components that include top or bottom margin (or in the case of content-main: padding). What options do we have for coming up with global approaches to spacing between components? Should we rely on the component margin and make sure that's nailed down correctly? 

I noticed that we're using the Fieldset component. Have we added that to the list of the components we're working on verifying?

**Comment by natalia-fitzgerald** [comment]
Hi @meissadia 
@billhimmelsbach and I talked through this at the weekly meeting. This prototype includes non-verified components so we don't want to publish it. We'd like to keep the PR open until @shindigira returns so he can check it out.
