### ISSUE TITLE
[Task] Verify Banner component

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-system-react#213]
Verify banner component to be used in the component library

### Context
Depends on verification of the Tagline component: https://github.com/cfpb/design-system-react/issues/205
![Screenshot 2023-10-12 at 11 30 15 AM](https://github.com/cfpb/sbl-project/assets/19983248/b62f72b3-3e4f-4966-9a6b-6160ffa93670)

### Verify the CFPB Design System (React) component against the CFPB Design System
- [ ] Has component intro text copied from the DS page
- [ ] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [ ] Each DS variant is implemented as a separate story
  - [ ] Story name should be sentence case (ex. List Link => List link)
  - [ ] Naming is consistent with the DS
  - [ ] Same component names, same placeholder text, etc.
- [ ] Order of stories matches between DS/DSR
- [ ] Component is built correctly
  - [ ] Visually compare DSR implementation to DS
  - [ ] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [ ] Manual visual review has been conducted and component has passed this review

### Run accessibility checks 
- [ ] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [ ] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [ ] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [ ] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [ ] Does the component have similar screen reader behavior as the sample components in WCAG, WebAIM, or similar accessibility examples?
- [ ] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [ ] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)
  
### Conduct PR review
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

### Verify component
- [ ] Move component to verified in Storybook

**Comment by meissadia** [comment]
In the DS this component is known as the `Tagline`.

We have two DSR components (Banner, Tagline) that duplicate functionality. 
 
- [Banner: Flag + text + optional links + phone number](https://cfpb.github.io/design-system-react/?path=/docs/components-draft-banners--overview)
  - Found in the header of https://www.consumerfinance.gov/
- [Tagline: Flag + text](https://cfpb.github.io/design-system-react/?path=/docs/components-draft-taglines--overview)
  - Found in the footer of https://www.consumerfinance.gov/


---
The [DS Tagline docs](https://cfpb.github.io/design-system/patterns/taglines) do not include the design for the version with links (DSR's `Banner`).  

The DS does include the component `m-global-eyebrow`, which is what is used on CF.gov
  - HTML:  [global-eyebrow.html](https://github.com/cfpb/design-system/blob/main/docs/_includes/global-eyebrow.html)
  - Styles: [global-eyebrow.less](https://github.com/cfpb/design-system/blob/main/docs/assets/css/global-eyebrow.less)
 ---

@natalia-fitzgerald 

I plant to consolidate our DSR components under the component name `Tagline`

Questions:
- Can we include the DSR Banner's additional features (links + phone number) in the consolidated DSR `Tagline`?
- Do we want to port this consolidation back to the DS?
  - Change classnames (eyebrow => tagline)?
  - Expand documentation to include variant with links + phone number?

**Comment by natalia-fitzgerald** [comment]
@meissadia 

First off I want to confirm my understanding of what you posted above. 

## Existing components (CFPB DS/consumerfinance.gov)
### m-global-eyebrow
- `m-global-eyebrow` is the flag, plus the text, plus the gray background and bottom border
- It does not include the languages links or the Submit a complaint phone number 
- When you say the DS includes the `m-global-eyebrow` you specifically mean the CFPB DS code and not the CFPB DS website, correct? 
<img width="900" alt="Screenshot 2023-10-27 at 10 50 40 AM" src="https://github.com/cfpb/design-system-react/assets/77348967/925d57ea-5072-4e50-b367-458429f3ddb7">

```
<div class="m-global-eyebrow">
    <div class="a-tagline">
        <span class="u-usa-flag"></span>
        <div>
            An official website of the
            <span class="u-nowrap">United States government</span>
        </div>
    </div>
</div>
```

```
.m-global-eyebrow {
  font-size: unit((12px / @base-font-size-px), em);
  padding-top: unit((@grid_gutter-width / 3 / @base-font-size-px), em);
  padding-bottom: unit((@grid_gutter-width / 3 / @base-font-size-px), em);
  background: @gray-5;
  border-bottom: 1px solid @gray-40;
}
```

## a-tagline
- `a-tagline` is the flag plus the text
- This component is included in the CFPB DS code AND on the CFPB DS website/documentation
<img width="817" alt="Screenshot 2023-10-27 at 10 56 41 AM" src="https://github.com/cfpb/design-system-react/assets/77348967/fd504d3a-9aaa-4a86-8700-64ea9ff2ce09">
`<div class="a-tagline">
              <span class="u-usa-flag"></span>
              <div class="a-tagline_text">
                  An official website of the
                  <span class="u-nowrap">United States government</span>
              </div>
          </div>'

In thinking about this I would first like to focus on the CFPB Design System and what is on consumerfinance.gov (and put the DSR previous implementations aside for a moment). 

First off I'd like to confirm the needs I can identify at this time, based on our SBL layouts: 
We will need a component that matches: 
- `m-global-eyebrow`: the flag, plus the text, plus the gray background and bottom border
- `a-tagline`: the flag plus the text
- `m-global-eyebrow` plus the languages links and the Submit a complaint phone number

## Component naming
In thinking about the naming of these components I took a look at a few other federal government design systems to see how they handle these nearly identical components. 

### USWDS
Name: Banner
Name in code: usa-banner
https://designsystem.digital.gov/components/banner/
<img width="1102" alt="Screenshot 2023-10-27 at 11 19 20 AM" src="https://github.com/cfpb/design-system-react/assets/77348967/9caf4b4c-9476-48f1-ba0e-3a0cc5d318ee">

### Veteran's Affairs
Name: banner - official gov
Name in code: va-official-gov-banner
https://design.va.gov/components/banner/official-gov
<img width="932" alt="Screenshot 2023-10-27 at 11 19 35 AM" src="https://github.com/cfpb/design-system-react/assets/77348967/7f9649eb-8712-4c2b-877d-ced2b2b17a4e">

If we decide to add `.m-global-eyebrow` as a component to the CFPB DS website we may want to consider either giving it a more descriptive name in the code (alluding to the usa, or official gov, or gov, etc) or, at least, giving it a name like this in the documentation site. Regardless this brings up an important question - how do we handle components that are included in the CFPB DS codebase but not on the CFGPB DS documentation website (i.e. visually listed as a component on the website). And, what is the approach to determining what is or isn't included in the CFPB DS website.

**Comment by natalia-fitzgerald** [comment]
Shifting this one to @billhimmelsbach since he's working on the Tagline.
