### ISSUE TITLE
[Task] Verify Links Component

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-system-react#215]
Verify links component to be used in the component library

### Verify the CFPB Design System (React) component against the CFPB Design System
- [x] Has component intro text copied from the DS page
- [x] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [x] Each DS variant is implemented as a separate story
  - [x] Story name should be sentence case (ex. List Link => List link)
  - [x] Naming is consistent with the DS
  - [x] Same component names, same placeholder text, etc.
- [x] Order of stories matches between DS/DSR
- [x] Component is built correctly
  - [x] Visually compare DSR implementation to DS
  - [x] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [x] Manual visual review has been conducted and component has passed this review

### Run accessibility checks 
- [x] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [x] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [x] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [ ] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [x] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [ ] Does the component have similar screen reader behavior as the sample components in WCAG, WebAIM, or similar accessibility examples?
- [ ] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [x] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)
  
### Conduct PR review
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

### Verify component
- [ ] Move component to verified in Storybook

## Context
https://cfpb.github.io/design-system/components/links
![Screenshot 2023-10-12 at 11 34 44 AM](https://github.com/cfpb/sbl-project/assets/19983248/053ff639-1643-4e3f-96d4-23ba1a12823e)

**Comment by meissadia** [comment]
TODO:
- [ ] Add alt text for Icons? Or should this be a separate PR
- [ ] Unit tests

**Comment by meissadia** [comment]
Reopening to get final Verification

**Comment by natalia-fitzgerald** [comment]
@meissadia 
The component is looking good! I made some text updates to the CFPB Design System page that I'd like to incorporate into the DSR page.

**New intro text:** 
Links are navigational elements that connect users to other locations, either on the current page or to a different page or site. In contrast, [buttons](https://cfpb.github.io/design-system/components/buttons) are used to signal important actions.

**Stories**
- Inline link~~s~~
- List link ~~Call-to-action links~~
  - Change code example for the links to "List link 1" "List link 2"
- Destructive link~~s~~
  - Change code example link text to "Destructive link" (remove the word "Sample"
- Link with icon~~Standard link with icon~~
- Non-wrapping link with icon ~~icon links~~
- Jump link
  - Change code example for the link to "Jump link" (remove the word "default")
- Jump link with icon on the left 
- Printed link~~s~~ (Should we want to add this to the DSR?)

**Comment by meissadia** [comment]
Reopening to remove Print example
