### ISSUE TITLE
[Task] Create Tests for List Component

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/design-system-react#222]
The [List component](https://cfpb.github.io/design-system-react/?path=/docs/components-draft-lists--overview) doesn't have tests written for it yet, and it would be great to establish some basic tests to check that it renders correctly. I'm imagining 5 test cases to start based on the code below:

https://github.com/cfpb/design-system-react/blob/c0678a225b93d114ca24c5f914d5f391dc2865a9/src/components/List/List.tsx#L22-L28

This issue would be completed if the following tests are written:

1. `m-list__horizontal` class is added to `List` when `isHorizontal` prop is passed in
2. `m-list__links` class is added to `List` when `isLinks` prop is passed in
3. `m-list__spaced` class is added to `List` when `isSpaced` prop is passed in
4. `m-list__unstyled` class is added to `List` when `isUnstyled` prop is passed in

5. `<ol>` list is rendered when `isOrdered` prop is passed in

Add these 5 render tests into a file called `List.test.tsx` in the same folder as `List.tsx`.

The tests could look very similar to other basic rendering tests in the codebase like [these label tests](https://github.com/cfpb/design-system-react/blob/main/src/components/Label/Label.test.tsx#L17).

Let me know if you have any questions! 👍

**Comment by alberturria** [comment]
Hey @billhimmelsbach , may I take this issue? :pray:

**Comment by billhimmelsbach** [comment]
Hi @alberturria! 👋

You definitely can, and thank you! I'll review [your PR](https://github.com/cfpb/design-system-react/pull/234) tonight.
