### ISSUE TITLE
[Github] Remove CODEOWNERS

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-system-react#254]
Currently, with the inclusion of the `.github/CODEOWNERS` file, Github requires a member of that list to approve a PR in order to get it merged.

To maximize flexibility and avoid blockers we want to allow all repo admins to approve a PR and have it then be mergeable.  

As far as I can tell, we can't disable this requirement so long as this file exists. 
 
If we still want some approval protection, [this is the only setting I see that seems to relate](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-pull-request-reviews-in-your-repository):
![Image](https://github.com/cfpb/design-system-react/assets/2592907/53e4d8b3-5634-4b3a-9104-b179b1a9a672)

**Comment by meissadia** [comment]
Settings updated

**Comment by billhimmelsbach** [comment]
Thanks for bringing this up @meissadia!
