### ISSUE TITLE
[Task] Align Unauthenticated Landing Page to MVP Discussion

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/design-system-react#261]
Align Unauthenticated Landing Page to MVP Discussion

![Image](https://github.com/cfpb/design-system-react/assets/19983248/af618d43-051e-4fd6-8aec-8caa823701ed)

Discussion on Mural

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
The visual (above) is no longer accurate. You can refer to the Figma file or the screenshots in the epic issue for reference.
