### ISSUE TITLE
[Meta] Rename this repo. Maybe "react-cfpb"?

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-system-react#56]
- [x] Rename repo
- [x] Update SBL Frontend to use new package/repo
- [ ] Fix [Github Pages deployment](https://cfpb.github.io/design-system-react/) of Storybook site

**Comment by meissadia** [comment]
Would want it to be easily discoverable when folks are looking through the CFPB repos related to design, and make it clear that it implements the DS, so I would go with a `design-*` name.

- design-system-react
- design-react
- design-react-lib

**Comment by contolini** [comment]
We also need a package name for npm. For comparison, the DS code is available at `@cfpb/cfpb-design-system`. I'm not sure why `cfpb` is in there twice, seems redundant. Naming this library `@cfpb/cfpb-design-system-react` is too verbose IMHO.

Maybe `@cfpb/design-components`?

**Comment by meissadia** [comment]
> Maybe `@cfpb/design-components`?

Could this be confusing since the CFPB design system already has the concept of [components](https://cfpb.github.io/design-system/components/)?  At the same time, it fits beautifully since we're implementing the React component version of CFPB DS components....but the fact that they are React specific components feels important. 

`@cfpb/design-components-react`?
`@cfpb/design-system-react`?

**Comment by anselmbradford** [comment]
<img width="551" alt="Screen Shot 2023-05-11 at 5 42 22 PM" src="https://github.com/cfpb/design-stories/assets/704760/c9dbba89-7faf-4f4e-a0d1-ea8058dc60b5">

https://github.com/cfpb/design-system/pull/360/commits/c5ed1312cfa258c407edf429feba33f869c5ff56

**Comment by natalia-fitzgerald** [comment]
I agree with @meissadia that "React" seems important. `@cfpb/design-system-react` may be the clearest way to go. I could alternately see an argument for `@cfpb/design-components-react` but you may lose that this library is specifically a React version of the Design System (components) and not just a new library of CFPB components. The last option which seems to get a little verbose but is perhaps the most crystal clear would be `@cfpb/design-system-components-react`

**Comment by meissadia** [comment]
I vote we pull the trigger on renaming it `@cfpb/design-system-react`.  
Then we can refer to the Design System as "DS" and the React implementation as "DSR". 

@contolini Sure, the package name `@cfpb/cfpb-design-system-react` is a bit long, but it's clear, and devs are going to copy/paste it anyway.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
I support the name you have proposed: `@cfpb/design-system-react`.

**Comment by contolini** [comment]
The github pages bug should be fixed after the couple of commits I added to https://github.com/cfpb/design-system-react/pull/159 get merged.

**Comment by meissadia** [comment]
> The github pages bug should be fixed after the couple of commits I added to #159 get merged.

Many thanks!
